name: CI Pipeline

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  php-lint:
    name: Lint PHP Files
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.1

      - name: Run PHP Lint
        run: |
          sudo apt-get install php-cli
          find ./ -name "*.php" -exec php -l {} \;

  js-lint:
    name: Lint JavaScript Files
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install ESLint
        run: npm install eslint --global

      - name: Debug ESLint Files
        run: ls assets/js/**/*.js

      - name: Run ESLint
        run: eslint "assets/js/**/*.js"  --env browser --env es2021 --rule "no-unused-vars:warn"